### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ravirajblr** [Gruveo/gruveo-embed-api-examples#1]
Upon running  
SSL="true" npm start
get the below error

ubuntu@ip-172-31-13-76:/var/www/html/basic-demo$ SSL="true" npm start

> gruveo-embed-api-examples@1.0.0 start /var/www/html/basic-demo
> node ./server

/var/www/html/basic-demo/server/index.js:42
const ssl = ['1', 'true', 'yes', 'on', 'enable'].includes(process.env.SSL);
                                                 ^

TypeError: ["1","true","yes","on","enable"].includes is not a function
    at Object.<anonymous> (/var/www/html/basic-demo/server/index.js:42:50)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-1035-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gruveo-embed-api-examples@1.0.0 start: `node ./server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gruveo-embed-api-examples@1.0.0 start script 'node ./server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gruveo-embed-api-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gruveo-embed-api-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gruveo-embed-api-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/basic-demo/npm-debug.log
[npm-debug.log](https://github.com/Gruveo/gruveo-embed-api-examples/files/1356173/npm-debug.log)

**Comment by zdila** [comment]
Thanks for the report.
