### ISSUE TITLE
No support for chat

### ISSUE THREAD

**Issue by hamzaruknuddin1** [Gruveo/gruveo-embed-api-examples#2]
Cannot find support for chat in this tutorial

**Comment by artmatsak** [comment]
To open the chat panel, please tap the chat (rightmost) button in the control bar during a call.

**Comment by artmatsak** [comment]
Disregard, the demo uses chromeless mode for the Gruveo embed, which disables most UI controls. To see the control bar, set `chromeless` to `false` [here](https://github.com/Gruveo/gruveo-embed-api-examples/blob/ed958a6fd694ce76a58f9e4a31158de1078a9958/basic-demo/static/script.js#L16).
